# Generated by Django 2.2.3 on 2019-09-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_restaurant_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
